### ISSUE TITLE
Bad output on Intel HD Graphics 4000 (OpenCL 1.1/1.2)

### ISSUE THREAD

**Issue by gingerbeardman** [palle-k/Mandelbrot#1]
macOS 10.14.6 Mojave

![Screen shot 2020-02-29 at 00 25 41](https://user-images.githubusercontent.com/49612/75596815-0db25880-5a8a-11ea-9507-1b41ff7b3319.png)

**Comment by palle-k** [comment]
I've pushed some changes that fix issues that I had on Intel UHD Graphics 630. Maybe your issues will be fixed by that as well.

I can't reproduce your issue, so there is not much I can do.

**Comment by gingerbeardman** [comment]
Understood.

Sadly I just get black screen now. I can see the crosshairs when I click but no fractal.

Never mind.

![Screen shot 2020-03-07 at 10 42 05](https://user-images.githubusercontent.com/49612/76141945-843df000-6060-11ea-9f90-a35076cad035.png)

**Comment by palle-k** [comment]
I dug out my old MacBook Pro, which has a HD Graphics 4000 and I was able to reproduce this issue. The HD Graphics 4000 does not support double precision. 

If you change `typedef double real_t` to `typedef float real_t` in the file kernels.cl (line 27), it should work. However, you will not be able to zoom in very far.

**Comment by gingerbeardman** [comment]
Thanks! Now I see it. Cheers to you.
